# Generated by OmopViewer 0.4.0
# Be careful editing this file

library(bslib)
library(dplyr)
library(DT)
library(gt)
library(markdown)
library(omopgenerics)
library(plotly)
library(purrr)
library(readr)
library(rlang)
library(shiny)
library(shinycssloaders)
library(shinyTree)
library(shinyWidgets)
library(sortable)
library(tidyr)
library(visOmopResults)
library(yaml)
library(EmpiricalCalibration)
library(forestplot)
library(systemfonts)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "shinyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "data", "preprocess.R"))
}

# uncomment to load the raw data
# rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "data"))

# load shiny data
load(fileData)

choices$summarise_large_scale_characteristics_table_name <- data[["summarise_large_scale_characteristics"]] |> omopgenerics::settings() |> dplyr::pull("table_name") |> unique()
selected$summarise_large_scale_characteristics_table_name <- data[["summarise_large_scale_characteristics"]] |> omopgenerics::settings() |> dplyr::pull("table_name") |> unique()
values$summarise_large_scale_characteristics_table_name <- data[["summarise_large_scale_characteristics"]] |> omopgenerics::settings() |> dplyr::pull("table_name") |> unique()

# source functions
source(file.path(getwd(), "functions.R"))
