# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    
    events_summary = FALSE,
    followup_summary = FALSE,
    survival_summary = FALSE,
    hr_summary = FALSE, 
    lasso_summary = FALSE,
    summarise_cohort_count = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE,
    summarise_large_scale_characteristics = FALSE
  )
  # lasso_summary -----
  
  shiny::observeEvent(input$lasso_summary_cdm_name,
                      {
                        updateButtons$lasso_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$lasso_summary_cohort,
                      {
                        updateButtons$lasso_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )

  shiny::observeEvent(input$events_summary_estimate_name,
                      {
                        updateButtons$lasso_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )

  shiny::observeEvent(updateButtons$lasso_summary, {
    if (updateButtons$lasso_summary == TRUE) {
      output$update_message_lasso_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_lasso_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_lasso_summary, {
    updateButtons$lasso_summary <- FALSE
  })
  
  ## get coefs of ps 
  getSelectedFeaturesSummaryData <- shiny::eventReactive(input$update_lasso_summary, {
    data[["selected_features"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$lasso_summary_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$lasso_summary_cohort) |>
      omopgenerics::filterAdditional(.data$window %in% input$lasso_summary_window) |>
      dplyr::mutate(estimate_type = "numeric")
  })
  getSelectedFeaturesSummaryTidy <- shiny::reactive({
    tidyDT(getSelectedFeaturesSummaryData() , 
           columns = c("cdm_name","cohort","variable_name", "variable_level", "event X=1", "variable","window", "concept_name", "domain_id"),
           pivotEstimates = input$selected_features_summary_tidy_pivot_estimates, 
           pivotVariables = input$selected_features_summary_tidy_pivot_estimates)
  })
  output$selected_features_summary_tidy <- DT::renderDT({
    getSelectedFeaturesSummaryTidy()
  })
  output$selcted_features_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSelectedFeaturesSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
   
  ## get asmd
  getASMDSummaryData <- shiny::eventReactive(input$update_lasso_summary, {
    dat1 <- data[["asmd"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$lasso_summary_cdm_name
      ) |>
      omopgenerics::filterGroup(grepl("matched",.data$cohort)) |>
      dplyr::mutate(estimate_name = paste(.data$estimate_name, "after_matching", sep = "_"), 
                    group_level = sub("_matched$", "", .data$group_level) )
    
    dat2 <- data[["asmd"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$lasso_summary_cdm_name
      ) |>
      omopgenerics::filterGroup(!grepl("matched",.data$cohort))
    
    dat <- omopgenerics::bind(dat2, dat1) |>
      omopgenerics::filterGroup(.data$cohort %in% input$lasso_summary_cohort)
    ac <- omopgenerics::additionalColumns(dat)
    dat |> omopgenerics::splitAdditional() |>
      tidyr::separate(variable_level, into = c("variable_level", "window"), sep = "_", extra = "merge", fill = "right") |>
      dplyr::left_join(data[["selected_features"]] |> 
      omopgenerics::tidy() |>
      dplyr::distinct(variable, concept_name), 
      by = c("variable_level" = "variable")) |>
      omopgenerics::uniteAdditional(cols = c(ac, "concept_name", "window")) |>
      omopgenerics::newSummarisedResult()
    
    
  })
  getASMDSummaryTidy <- shiny::reactive({
    tidyDT(getASMDSummaryData()|> 
             dplyr::filter(.data$variable_level %in% input$asmd_summary_covariate)|> 
             omopgenerics::filterAdditional(.data$window %in%  input$asmd_summary_window),
           columns = c("cdm_name","cohort", "covariate", "variable_name", "variable_level","concept_name","window" ,"event", "comparator"),
           pivotEstimates = input$asmd_summary_tidy_pivot_estimates, 
           pivotVariables = input$asmd_summary_tidy_pivot_estimates)
  })
  output$asmd_summary_tidy <- DT::renderDT({
    getASMDSummaryTidy()
  })
  output$asmd_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getASMDSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  
  ## get distribution of ps
  getDistributionPSData <- shiny::eventReactive(input$update_lasso_summary, {
    data[["distribution_ps"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$lasso_summary_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$lasso_summary_cohort)
  })
  
  getDistributionPSPlot <- shiny::reactive({
   plot_df <- getDistributionPSData() |>
      omopgenerics::tidy() |>
      dplyr::mutate(
        treatment = factor(as.character(.data$treatment),
                           levels = c("0","1"),
                           labels = c("EBRT","Radical prostatectomy"))
      ) %>%
      dplyr::arrange(.data$treatment, .data$density_x)
    
    ggplot2::ggplot(plot_df, aes(x = .data$density_x, y = .data$density_y,
                        fill = .data$treatment, colour = .data$treatment, group = .data$treatment)) +
      ggplot2::geom_area(alpha = 0.25, position = "identity", colour = NA) +
      ggplot2::geom_line() +
      ggplot2::scale_x_continuous(limits = c(0, 1)) +
      ggplot2::labs(x = "Propensity score", y = "Density", colour = "Treatment", fill = "Treatment") +
      ggplot2::theme_minimal() +
      ggplot2::facet_wrap(input$distribution_ps_facet, scales = "free_y")
  
  })
  
  
  
  output$distribution_ps_plot <- shiny::renderPlot({  
    getDistributionPSPlot()
  })
  
  
  # events_summary -----
  ## update message if filter is changed
  shiny::observeEvent(input$events_summary_cdm_name,
    {
      updateButtons$events_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$events_summary_cohort,
                      {
                        updateButtons$events_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$events_summary_treatment,
    {
      updateButtons$events_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$events_summary_outcome,
    {
      updateButtons$events_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$events_summary_variable_name,
    {
      updateButtons$events_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$events_summary_estimate_name,
    {
      updateButtons$events_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$events_summary, {
    if (updateButtons$events_summary == TRUE) {
      output$update_message_events_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_events_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_events_summary, {
    updateButtons$events_summary <- FALSE
  })

  ## get events_summary data
  getEventsSummaryData <- shiny::eventReactive(input$update_events_summary, {
    data[["events_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$events_summary_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$events_summary_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$events_summary_outcome) |>
      dplyr::filter(.data$variable_level %in% input$events_summary_treatment)
  })
  getEventsSummaryTidy <- shiny::reactive({
    tidyDT(getEventsSummaryData(), 
           columns = c("cdm_name","cohort", "treatment", "outcome", "variable_name", "variable_level"),
           pivotEstimates = input$events_summary_tidy_pivot_estimates, 
           pivotVariables = input$events_summary_tidy_pivot_estimates)
  })
  output$events_summary_tidy <- DT::renderDT({
    getEventsSummaryTidy()
  })
  output$events_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getEventsSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getEventsSummaryTable <- shiny::reactive({
    getEventsSummaryData() |>
      simpleTable(
        header = "cdm_name",
        group = c("cohort","outcome"), 
        hide = "variable_name",
        rename = c("Treatment" = "variable_level")
      )
  })
  output$events_summary_table <- gt::render_gt({
    getEventsSummaryTable()
  })
  output$events_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$events_summary_table_format),
    content = function(file) {
      gt::gtsave(getEventsSummaryTable(), file)
    }
  )
  # followup_summary -----
  ## update message if filter is changed
  shiny::observeEvent(input$followup_summary_cdm_name,
    {
      updateButtons$followup_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$followup_summary_treatment,
    {
      updateButtons$followup_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$followup_summary_outcome,
    {
      updateButtons$followup_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$followup_summary_cohort,
                      {
                        updateButtons$followup_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$followup_summary_reason,
    {
      updateButtons$followup_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$followup_summary_variable_name,
    {
      updateButtons$followup_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$followup_summary_estimate_name,
    {
      updateButtons$followup_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$followup_summary, {
    if (updateButtons$followup_summary == TRUE) {
      output$update_message_followup_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_followup_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_followup_summary, {
    updateButtons$followup_summary <- FALSE
  })

  ## get followup_summary data
  getFollowupSummaryData <- shiny::eventReactive(input$update_followup_summary, {
    data[["followup_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$followup_summary_cdm_name,
        .data$estimate_name %in% input$followup_summary_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$followup_summary_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$followup_summary_outcome) |>
      omopgenerics::filterAdditional(.data$reason %in% input$followup_summary_reason) |>
      dplyr::filter(.data$variable_level %in% input$events_summary_treatment)
  })
  getFollowupSummaryTidy <- shiny::reactive({
    tidyDT(getFollowupSummaryData(), 
           columns = c("cdm_name","cohort", "treatment", "outcome", "variable_name", "variable_level", "reason"),
           pivotEstimates = input$events_summary_tidy_pivot_estimates, 
           pivotVariables = input$followup_summary_tidy_pivot_estimates)
  })
  output$followup_summary_tidy <- DT::renderDT({
    getFollowupSummaryTidy()
  })
  output$followup_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getFollowupSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getFollowupSummaryTable <- shiny::reactive({
    getFollowupSummaryData() |>
      dplyr::relocate("group_name", "group_level", "variable_name", "variable_level", "additional_name", "additional_level", dplyr::everything()) |>
      dplyr::arrange(.data$variable_level, .data$additional_level) |>
      simpleTable(
        header = "cdm_name",
        group = c("cohort", "outcome"), 
        hide = "variable_name", 
        rename = c("Treatment" = "variable_level")
      )
  })
  output$followup_summary_table <- gt::render_gt({
    getFollowupSummaryTable()
  })
  output$followup_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$followup_summary_table_format),
    content = function(file) {
      gt::gtsave(getFollowupSummaryTable(), file)
    }
  )
  # survival_summary -----
  ## update message if filter is changed
  shiny::observeEvent(input$survival_summary_cdm_name,
    {
      updateButtons$survival_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$survival_summary_cohort,
                      {
                        updateButtons$survival_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$survival_summary_treatment,
    {
      updateButtons$survival_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$survival_summary_outcome,
    {
      updateButtons$survival_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$survival_summary_variable_name,
    {
      updateButtons$survival_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$survival_summary_estimate_name,
    {
      updateButtons$survival_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$survival_summary_time_limit,
    {
      updateButtons$survival_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$survival_summary, {
    if (updateButtons$survival_summary == TRUE) {
      output$update_message_survival_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_survival_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_survival_summary, {
    updateButtons$survival_summary <- FALSE
  })

  ## get survival_summary data
  getSurvivalSummaryData <- shiny::eventReactive(input$update_survival_summary, {
    time_limit <- timeLimitFromInput( input$survival_summary_time_limit)
    cols <- omopgenerics::additionalColumns(data[["survival_summary"]])
    data[["survival_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$survival_summary_cdm_name,
        .data$estimate_name %in% input$survival_summary_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$survival_summary_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$survival_summary_outcome) |> 
      dplyr::filter(.data$variable_level %in% input$events_summary_treatment) |>
      omopgenerics::splitAdditional() |> 
      dplyr::filter(as.numeric(.data$time) < .env$time_limit) |>
      omopgenerics::uniteAdditional(cols = cols)
  })
  getSurvivalSummaryTidy <- shiny::reactive({
    tidyDT(getSurvivalSummaryData() , 
           columns = c("cdm_name", "treatment", "outcome", "time", "variable_name", "variable_level"), 
           pivotEstimates = input$survival_summary_tidy_pivot_estimates, 
           pivotVariables = input$survival_summary_tidy_pivot_estimates)
  })
  output$survival_summary_tidy <- DT::renderDT({
    getSurvivalSummaryTidy()
  })
  output$survival_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSurvivalSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSurvivalSummaryTable <- shiny::reactive({
    getSurvivalSummaryData() |>
      simpleTable(
        header = input$survival_summary_table_header,
        group = input$survival_summary_table_group_column,
        hide = input$survival_summary_table_hide
      )
  })
  output$survival_summary_table <- gt::render_gt({
    getSurvivalSummaryTable()
  })
  output$survival_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$survival_summary_table_format),
    content = function(file) {
      gt::gtsave(getSurvivalSummaryTable(), file)
    }
  )
  getSurvivalPlot <- shiny::reactive({
    df <- getSurvivalSummaryData() |>
      omopgenerics::tidy() |>
      dplyr::rename("treatment" = "variable_level") |>
      dplyr::filter(
        .data$cdm_name %in% input$survival_summary_cdm_name,
        .data$outcome  %in% input$survival_summary_outcome
      )
      
    
    # Decide facets based on distinct levels present
    facet_row <- if (dplyr::n_distinct(df$cdm_name, na.rm = TRUE) > 1) "cdm_name" else "."
    facet_col <- if (dplyr::n_distinct(df$outcome,  na.rm = TRUE) > 1) "outcome"  else "."
    facets <- stats::as.formula(paste(facet_row, "~", facet_col))
    
    # Ensure time is numeric and ordered; drop groups with only 1 row (cannot draw a path)
    df <- df |>
      dplyr::mutate(time = as.numeric(.data$time)) |>
      dplyr::group_by(.data$cdm_name, .data$outcome, .data$treatment) |>
      dplyr::arrange(.data$time, .by_group = TRUE) |>
      dplyr::filter(dplyr::n() > 1) |>
      dplyr::ungroup()
    
    shiny::validate(
      shiny::need(nrow(df) > 0, "Not enough points per group to draw lines. Try widening filters.")
    )
    
    df |>
      ggplot2::ggplot(
        ggplot2::aes(
          x = .data$time,
          y = .data$survival,
          ymin = .data$lower_survival,
          ymax = .data$upper_survival,
          colour = .data$treatment,
          fill   = .data$treatment,
          group  = .data$treatment   # <-- key for line/ribbon grouping
        )
      ) +
      ggplot2::geom_step(direction = "hv") +
      ggplot2::geom_ribbon(alpha = 0.2, colour = NA) +
      ggplot2::facet_grid(facets) +
      ggplot2::theme(legend.position = "top")
  })
  
  
  
  output$survival_plot <- shiny::renderPlot({  
    getSurvivalPlot()
  })
 
  getLogMinusLogPlot <- shiny::reactive({
    df <- getSurvivalSummaryData() |>
      omopgenerics::tidy() |>
      dplyr::rename("treatment" = "variable_level") |>
      dplyr::filter(
        .data$cdm_name %in% input$survival_summary_cdm_name,
        .data$outcome  %in% input$survival_summary_outcome
      )
    
    facet_row <- if (dplyr::n_distinct(df$cdm_name, na.rm = TRUE) > 1) "cdm_name" else "."
    facet_col <- if (dplyr::n_distinct(df$outcome,  na.rm = TRUE) > 1) "outcome"  else "."
    facets <- stats::as.formula(paste(facet_row, "~", facet_col))
    
    df <- df |>
      dplyr::mutate(time = as.numeric(.data$time)) |>
      dplyr::filter(.data$time > 0) |>
      dplyr::group_by(.data$cdm_name, .data$outcome, .data$treatment) |>
      dplyr::arrange(.data$time, .by_group = TRUE) |>
      dplyr::filter(dplyr::n() > 1) |>
      dplyr::ungroup() |>
      dplyr::filter(!is.na(.data$survival), .data$survival > 0, .data$survival < 1) |>
      dplyr::mutate(
        cloglog  = log(-log(.data$survival)),
        log_time = log(.data$time)
      )
    
    shiny::validate(
      shiny::need(nrow(df) > 0, "Not enough valid points to build a log(-log) plot.")
    )
    
    df |>
      ggplot2::ggplot(
        ggplot2::aes(
          x = .data$log_time,
          y = .data$cloglog,
          colour = .data$treatment,
          group  = .data$treatment
        )
      ) +
      ggplot2::geom_line(linewidth = 1) +  # clean lines only
      ggplot2::facet_grid(facets) +
      ggplot2::labs(
        x = "log(time)",
        y = "log(-log(survival))"
      ) +
      ggplot2::theme(legend.position = "top")
  })
  
  output$log_minus_log_plot <- shiny::renderPlot({  
    getLogMinusLogPlot()
  })
  

  
  # hr_summary -----
  ## update message if filter is changed
  shiny::observeEvent(input$hr_summary_cdm_name,
    {
      updateButtons$hr_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$hr_summary_cohort,
                      {
                        updateButtons$hr_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$hr_summary_variable,
    {
      updateButtons$hr_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$hr_summary_outcome,
    {
      updateButtons$hr_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$hr_summary_variable_name,
    {
      updateButtons$hr_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$hr_summary_estimate_name,
    {
      updateButtons$hr_summary <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$hr_summary, {
    if (updateButtons$hr_summary == TRUE) {
      output$update_message_hr_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_hr_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_hr_summary, {
    updateButtons$hr_summary <- FALSE
  })

  ## get hr_summary data
  getHrSummaryData <- shiny::eventReactive(input$update_hr_summary, {
    data[["hr_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$hr_summary_cdm_name,
        .data$estimate_name %in% input$hr_summary_estimate_name, 
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$hr_summary_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$hr_summary_outcome)
  })
  getHrSummaryTidy <- shiny::reactive({
    tidyDT(getHrSummaryData(), input$hr_summary_tidy_columns, input$hr_summary_tidy_pivot_estimates)
  })
  output$hr_summary_tidy <- DT::renderDT({
    getHrSummaryTidy()
  })
  output$hr_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getHrSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getHrSummaryTable <- shiny::reactive({
    getHrSummaryData() |>
      simpleTable(
        header = "cdm_name",
        group = c("cohort", "outcome"), 
        hide = "variable_name", 
        rename = c("Variable" = "variable_level")
      )
  })
  output$hr_summary_table <- gt::render_gt({
    getHrSummaryTable()
  })
  output$hr_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$hr_summary_table_format),
    content = function(file) {
      gt::gtsave(getHrSummaryTable(), file)
    }
  )
  
  getForestPlot <- shiny::reactive({
    df <- getHrSummaryData() |>
      omopgenerics::tidy() |> 
      dplyr::mutate(coef = as.numeric(.data$coef), 
                                            hr = as.numeric(.data$hr), 
                                            se_coef = as.numeric(.data$se_coef), 
                                            z = as.numeric(.data$z), 
                                            p = as.numeric(.data$p), 
                                            lower_hr = as.numeric(.data$lower_hr), 
                                            upper_hr = as.numeric(.data$upper_hr))
    table <- cbind(
      df$outcome,
      sprintf("%.3f (%.3f–%.3f)", df$hr, df$lower_hr, df$upper_hr)
    )
    forestplot(
      labeltext = table,
      mean = df$hr,
      lower = df$lower_hr,
      upper = df$upper_hr,
      zero = 1,
      boxsize = 0.2,
      xlab = "Hazard Ratio",
      title = "Hazard Ratios by Outcome"
    )

  })
  output$forest_plot <- shiny::renderPlot({
    getForestPlot()
  })
  
  output$forest_plot_download <- shiny::downloadHandler(
    filename = "forest_plot.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getForestPlot(),
        width = as.numeric(input$forest_plot_width),
        height = as.numeric(input$forest_plot_height),
        units = input$forest_plot_units,
        dpi = as.numeric(input$forest_plot_dpi)
      )
    }
  )
  
  shiny::observe({
    updateButtons$summarise_cohort_overlap <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_overlap_cdm_name,
      input$summarise_cohort_overlap_cohort_name_reference,
      input$summarise_cohort_overlap_cohort_name_comparator,
      input$summarise_cohort_overlap_variable_name,
      input$summarise_cohort_overlap_estimate_name,
      input$summarise_cohort_overlap_overlap_by,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_overlap, {
    if (updateButtons$summarise_cohort_overlap == TRUE) {
      output$update_message_summarise_cohort_overlap <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_cohort_overlap <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_overlap, {
    updateButtons$summarise_cohort_overlap <- FALSE
  })
  
  ## get summarise_cohort_overlap data
  getSummariseCohortOverlapData <- shiny::eventReactive(input$update_summarise_cohort_overlap, {
    data[["summarise_cohort_overlap"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_overlap_cdm_name,
        .data$variable_name %in% input$summarise_cohort_overlap_variable_name,
        .data$estimate_name %in% input$summarise_cohort_overlap_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$cohort_name_reference %in% input$summarise_cohort_overlap_cohort_name_reference,
        .data$cohort_name_comparator %in% input$summarise_cohort_overlap_cohort_name_comparator
      ) |>
      omopgenerics::filterSettings(.data$overlap_by %in% input$summarise_cohort_overlap_overlap_by)
  })
  getSummariseCohortOverlapTable <- shiny::reactive({
    getSummariseCohortOverlapData() |>
      CohortCharacteristics::tableCohortOverlap(
        uniqueCombinations = input$summarise_cohort_overlap_table_unique_combinations,
        header = input$summarise_cohort_overlap_table_header,
        groupColumn = input$summarise_cohort_overlap_table_group_column,
        hide = input$summarise_cohort_overlap_table_hide
      )
  })
  output$summarise_cohort_overlap_table <- gt::render_gt({
    getSummariseCohortOverlapTable()
  })
  output$summarise_cohort_overlap_table_download <- shiny::downloadHandler(
    filename = paste0("table_overlap.", input$summarise_cohort_overlap_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortOverlapTable(), file)
    }
  )
  getSummariseCohortOverlapPlot <- shiny::reactive({
    getSummariseCohortOverlapData() |>
      CohortCharacteristics::plotCohortOverlap(
        facet = input$summarise_cohort_overlap_plot_facet
      )
  })
  output$summarise_cohort_overlap_plot <- shiny::renderUI({
    x <- getSummariseCohortOverlapPlot()
    renderInteractivePlot(x, input$summarise_cohort_overlap_plot_interactive)
  })
  output$summarise_cohort_overlap_plot_download <- shiny::downloadHandler(
    filename = "plot_overlap.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortOverlapPlot(),
        width = as.numeric(input$summarise_cohort_overlap_plot_width),
        height = as.numeric(input$summarise_cohort_overlap_plot_height),
        units = input$summarise_cohort_overlap_plot_units,
        dpi = as.numeric(input$summarise_cohort_overlap_plot_dpi)
      )
    }
  )
  # summarise_cohort_count -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_count <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_count_cdm_name,
      input$summarise_cohort_count_cohort_name,
      input$summarise_cohort_count_variable_name,
      input$summarise_cohort_count_table_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_count, {
    if (updateButtons$summarise_cohort_count == TRUE) {
      output$update_message_summarise_cohort_count <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_cohort_count <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_count, {
    updateButtons$summarise_cohort_count <- FALSE
  })
  
  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::eventReactive(input$update_summarise_cohort_count, {
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_cohort_count_table_name)
  })
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderUI({
    x <- getSummariseCohortCountPlot()
    renderInteractivePlot(x, input$summarise_cohort_count_plot_interactive)
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCohortCountPlot(),
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )
  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_attrition_cdm_name,
      input$summarise_cohort_attrition_cohort_name,
      input$summarise_cohort_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })
  
  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )
  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderText("Filters have changed please consider to use the update content button!")
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })
  
  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # summarise_large_scale_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_large_scale_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_large_scale_characteristics_cdm_name,
      input$summarise_large_scale_characteristics_cohort_name,
      input$summarise_large_scale_characteristics_variable_level,
      input$summarise_large_scale_characteristics_analysis,
      input$summarise_large_scale_characteristics_table_name,
      input$summarise_large_scale_characteristics_type,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_large_scale_characteristics, {
    if (updateButtons$summarise_large_scale_characteristics == TRUE) {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_large_scale_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_large_scale_characteristics, {
    updateButtons$summarise_large_scale_characteristics <- FALSE
  })
  
  ## get summarise_large_scale_characteristics data
  getSummariseLargeScaleCharacteristicsData <- shiny::eventReactive(input$update_summarise_large_scale_characteristics, {
    data[["summarise_large_scale_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_large_scale_characteristics_cdm_name,
        .data$variable_level %in% input$summarise_large_scale_characteristics_variable_level
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_large_scale_characteristics_cohort_name) |>
      omopgenerics::filterSettings(
        .data$analysis %in% input$summarise_large_scale_characteristics_analysis,
        .data$table_name %in% input$summarise_large_scale_characteristics_table_name,
        .data$type %in% input$summarise_large_scale_characteristics_type
      )
  })
  getSummariseLargeScaleCharacteristicsTableLsc <- shiny::reactive({
    if (identical(input$summarise_large_scale_characteristics_table_lsc_compare_by, "no compare")) {
      cb <- NULL
    } else {
      cb <- input$summarise_large_scale_characteristics_table_lsc_compare_by
    }
    if (identical(input$summarise_large_scale_characteristics_table_lsc_smd_reference, "no SMD")) {
      sr <- NULL
    } else {
      sr <- input$summarise_large_scale_characteristics_table_lsc_smd_reference
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableLargeScaleCharacteristics(
        compareBy = cb,
        hide = input$summarise_large_scale_characteristics_table_lsc_hide,
        smdReference = sr
      )
  })
  output$summarise_large_scale_characteristics_table_lsc <- reactable::renderReactable({
    getSummariseLargeScaleCharacteristicsTableLsc()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_table_lsc_compare_by, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_table_lsc_compare_by)]]
    opts <- c("no SMD", opts)
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_table_lsc_smd_reference",
      choices = opts,
      selected = "no SMD"
    )
  })
  output$summarise_large_scale_characteristics_table_lsc_download <- shiny::downloadHandler(
    filename = "smd_results.csv",
    content = function(file) {
      rt <- getSummariseLargeScaleCharacteristicsTableLsc()
      rt$x$tag$attribs$data |>
        unclass() |>
        jsonlite::fromJSON() |>
        dplyr::as_tibble() |>
        readr::write_csv(file)
    }
  )
  getSummariseLargeScaleCharacteristicsTableMostCommon <- shiny::reactive({
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::tableTopLargeScaleCharacteristics(
        topConcepts = input$summarise_large_scale_characteristics_table_most_common_top_concepts,
        type = "gt"
      )
  })
  output$summarise_large_scale_characteristics_table_most_common <- gt::render_gt({
    getSummariseLargeScaleCharacteristicsTableMostCommon()
  })
  output$summarise_large_scale_characteristics_table_most_common_download <- shiny::downloadHandler(
    filename = paste0("top_concepts.", input$summarise_large_scale_characteristics_table_most_common_format),
    content = function(file) {
      gt::gtsave(getSummariseLargeScaleCharacteristicsTableMostCommon(), file)
    }
  )
  getSummariseLargeScaleCharacteristicsPlotCompared <- shiny::reactive({
    if (input$summarise_large_scale_characteristics_plot_compared_missings) {
      mis <- 0
    } else {
      mis <- NULL
    }
    getSummariseLargeScaleCharacteristicsData() |>
      CohortCharacteristics::plotComparedLargeScaleCharacteristics(
        colour = input$summarise_large_scale_characteristics_plot_compared_colour,
        reference = input$summarise_large_scale_characteristics_plot_compared_reference,
        facet = input$summarise_large_scale_characteristics_plot_compared_facet,
        missings = mis
      )
  })
  output$summarise_large_scale_characteristics_plot_compared <- plotly::renderPlotly({
    getSummariseLargeScaleCharacteristicsPlotCompared()
  })
  shiny::observeEvent(input$summarise_large_scale_characteristics_plot_compared_colour, {
    opts <- values[[paste0("summarise_large_scale_characteristics_", input$summarise_large_scale_characteristics_plot_compared_colour)]]
    shinyWidgets::updatePickerInput(
      inputId = "summarise_large_scale_characteristics_plot_compared_reference",
      choices = opts,
      selected = opts[1]
    )
  })
  
  # nco_events_summary -----
  ## update message if filter is changed
  shiny::observeEvent(input$nco_events_summary_cdm_name,
                      {
                        updateButtons$nco_events_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_events_summary_cohort,
                      {
                        updateButtons$nco_events_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_events_summary_treatment,
                      {
                        updateButtons$events_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_events_summary_outcome,
                      {
                        updateButtons$nco_events_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_events_summary_variable_name,
                      {
                        updateButtons$nco_events_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_events_summary_estimate_name,
                      {
                        updateButtons$nco_events_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$nco_events_summary, {
    if (updateButtons$nco_events_summary == TRUE) {
      output$update_message_nco_events_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_nco_events_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_nco_events_summary, {
    updateButtons$nco_events_summary <- FALSE
  })
  
  ## get events_summary data
  getNCOEventsSummaryData <- shiny::eventReactive(input$update_nco_events_summary, {
    data[["nco_events_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$nco_events_summary_cdm_name
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$nco_events_summary_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$nco_events_summary_outcome) |>
      dplyr::filter(.data$variable_level %in% input$nco_events_summary_treatment)
  })
  getNCOEventsSummaryTidy <- shiny::reactive({
    tidyDT(getNCOEventsSummaryData(), 
           columns = c("cdm_name","cohort", "treatment", "outcome", "variable_name", "variable_level"),
           pivotEstimates = input$nco_events_summary_tidy_pivot_estimates, 
           pivotVariables = input$nco_events_summary_tidy_pivot_estimates)
  })
  output$nco_events_summary_tidy <- DT::renderDT({
    getNCOEventsSummaryTidy()
  })
  output$nco_events_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getNCOEventsSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getNCOEventsSummaryTable <- shiny::reactive({
    getNCOEventsSummaryData() |>
      simpleTable(
        header = "cdm_name",
        group = c("cohort","outcome"), 
        hide = "variable_name",
        rename = c("Treatment" = "variable_level")
      )
  })
  output$nco_events_summary_table <- gt::render_gt({
    getNCOEventsSummaryTable()
  })
  output$nco_events_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$nco_events_summary_table_format),
    content = function(file) {
      gt::gtsave(getNCOEventsSummaryTable(), file)
    }
  )
  # followup_summary -----
  ## update message if filter is changed
  shiny::observeEvent(input$nco_followup_summary_cdm_name,
                      {
                        updateButtons$nco_followup_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_followup_summary_treatment,
                      {
                        updateButtons$nco_followup_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_followup_summary_outcome,
                      {
                        updateButtons$nco_followup_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_followup_summary_cohort,
                      {
                        updateButtons$nco_followup_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_followup_summary_reason,
                      {
                        updateButtons$nco_followup_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_followup_summary_variable_name,
                      {
                        updateButtons$nco_followup_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_followup_summary_estimate_name,
                      {
                        updateButtons$nco_followup_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$nco_followup_summary, {
    if (updateButtons$nco_followup_summary == TRUE) {
      output$update_message_nco_followup_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_nco_followup_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_nco_followup_summary, {
    updateButtons$nco_followup_summary <- FALSE
  })
  
  ## get followup_summary data
  getNCOFollowupSummaryData <- shiny::eventReactive(input$update_nco_followup_summary, {
    data[["nco_followup_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$nco_followup_summary_cdm_name,
        .data$estimate_name %in% input$nco_followup_summary_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$nco_followup_summary_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$nco_followup_summary_outcome) |>
      omopgenerics::filterAdditional(.data$reason %in% input$nco_followup_summary_reason) |>
      dplyr::filter(.data$variable_level %in% input$nco_followup_summary_treatment)
  })
  getNCOFollowupSummaryTidy <- shiny::reactive({
    tidyDT(getNCOFollowupSummaryData(), 
           columns = c("cdm_name","cohort", "treatment", "outcome", "variable_name", "variable_level", "reason"),
           pivotEstimates = input$nco_followup_summary_tidy_pivot_estimates, 
           pivotVariables = input$nco_followup_summary_tidy_pivot_estimates)
  })
  output$nco_followup_summary_tidy <- DT::renderDT({
    getNCOFollowupSummaryTidy()
  })
  output$nco_followup_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_nco_followup.csv",
    content = function(file) {
      getNCOFollowupSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getNCOFollowupSummaryTable <- shiny::reactive({
    getNCOFollowupSummaryData() |>
      dplyr::relocate("group_name", "group_level", "variable_name", "variable_level", "additional_name", "additional_level", dplyr::everything()) |>
      dplyr::arrange(.data$variable_level, .data$additional_level) |>
      simpleTable(
        header = "cdm_name",
        group = c("cohort", "outcome"), 
        hide = "variable_name", 
        rename = c("Treatment" = "variable_level")
      )
  })
  output$nco_followup_summary_table <- gt::render_gt({
    getNCOFollowupSummaryTable()
  })
  output$nco_followup_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$nco_followup_summary_table_format),
    content = function(file) {
      gt::gtsave(getNCOFollowupSummaryTable(), file)
    }
  )
  # nco survival_summary -----
  ## update message if filter is changed
  shiny::observeEvent(input$nco_survival_summary_cdm_name,
                      {
                        updateButtons$nco_survival_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_survival_summary_cohort,
                      {
                        updateButtons$nco_survival_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_survival_summary_treatment,
                      {
                        updateButtons$nco_survival_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_survival_summary_outcome,
                      {
                        updateButtons$nco_survival_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_survival_summary_variable_name,
                      {
                        updateButtons$nco_survival_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_survival_summary_estimate_name,
                      {
                        updateButtons$nco_survival_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_survival_summary_time_limit,
                      {
                        updateButtons$nco_survival_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$nco_survival_summary, {
    if (updateButtons$nco_survival_summary == TRUE) {
      output$update_message_nco_survival_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_nco_survival_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_nco_survival_summary, {
    updateButtons$nco_survival_summary <- FALSE
  })
  
  ## get survival_summary data
  getNCOSurvivalSummaryData <- shiny::eventReactive(input$update_nco_survival_summary, {
    time_limit <- timeLimitFromInput( input$nco_survival_summary_time_limit)
    cols <- omopgenerics::additionalColumns(data[["nco_survival_summary"]])
    data[["nco_survival_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$nco_survival_summary_cdm_name,
        .data$estimate_name %in% input$nco_survival_summary_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$nco_survival_summary_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$nco_survival_summary_outcome) |> 
      dplyr::filter(.data$variable_level %in% input$nco_survival_summary_treatment) |>
      omopgenerics::splitAdditional() |> 
      dplyr::filter(as.numeric(.data$time) < .env$time_limit) |>
      omopgenerics::uniteAdditional(cols = cols)
  })
  getNCOSurvivalSummaryTidy <- shiny::reactive({
    tidyDT(getNCOSurvivalSummaryData() , 
           columns = c("cdm_name", "treatment", "outcome", "time", "variable_name", "variable_level"), 
           pivotEstimates = input$nco_survival_summary_tidy_pivot_estimates, 
           pivotVariables = input$nco_survival_summary_tidy_pivot_estimates)
  })
  output$nco_survival_summary_tidy <- DT::renderDT({
    getNCOSurvivalSummaryTidy()
  })
  output$nco_survival_summary_tidy_download <- shiny::downloadHandler(
    filename = "tidy_nco_survival.csv",
    content = function(file) {
      getNCOSurvivalSummaryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getNCOSurvivalSummaryTable <- shiny::reactive({
    getNCOSurvivalSummaryData() |>
      simpleTable(
        header = input$nco_survival_summary_table_header,
        group = input$nco_survival_summary_table_group_column,
        hide = input$nco_survival_summary_table_hide
      )
  })
  output$nco_survival_summary_table <- gt::render_gt({
    getNCOSurvivalSummaryTable()
  })
  output$nco_survival_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$nco_survival_summary_table_format),
    content = function(file) {
      gt::gtsave(getNCOSurvivalSummaryTable(), file)
    }
  )
  getNCOSurvivalPlot <- shiny::reactive({
    df <- getNCOSurvivalSummaryData() |>
      omopgenerics::tidy() |>
      dplyr::rename("treatment" = "variable_level") |>
      dplyr::filter(
        .data$cdm_name %in% input$nco_survival_summary_cdm_name,
        .data$outcome  %in% input$nco_survival_summary_outcome
      )
    
    
    # Decide facets based on distinct levels present
    facet_row <- if (dplyr::n_distinct(df$cdm_name, na.rm = TRUE) > 1) "cdm_name" else "."
    facet_col <- if (dplyr::n_distinct(df$outcome,  na.rm = TRUE) > 1) "outcome"  else "."
    facets <- stats::as.formula(paste(facet_row, "~", facet_col))
    
    # Ensure time is numeric and ordered; drop groups with only 1 row (cannot draw a path)
    df <- df |>
      dplyr::mutate(time = as.numeric(.data$time)) |>
      dplyr::group_by(.data$cdm_name, .data$outcome, .data$treatment) |>
      dplyr::arrange(.data$time, .by_group = TRUE) |>
      dplyr::filter(dplyr::n() > 1) |>
      dplyr::ungroup()
    
    shiny::validate(
      shiny::need(nrow(df) > 0, "Not enough points per group to draw lines. Try widening filters.")
    )
    
    df |>
      ggplot2::ggplot(
        ggplot2::aes(
          x = .data$time,
          y = .data$survival,
          ymin = .data$lower_survival,
          ymax = .data$upper_survival,
          colour = .data$treatment,
          fill   = .data$treatment,
          group  = .data$treatment   # <-- key for line/ribbon grouping
        )
      ) +
      ggplot2::geom_step(direction = "hv") +
      ggplot2::geom_ribbon(alpha = 0.2, colour = NA) +
      ggplot2::facet_grid(facets) +
      ggplot2::theme(legend.position = "top")
  })
  
  
  
  output$nco_survival_plot <- shiny::renderPlot({  
    getNCOSurvivalPlot()
  })
  
  getNCOLogMinusLogPlot <- shiny::reactive({
    df <- getNCOSurvivalSummaryData() |>
      omopgenerics::tidy() |>
      dplyr::rename("treatment" = "variable_level") |>
      dplyr::filter(
        .data$cdm_name %in% input$nco_survival_summary_cdm_name,
        .data$outcome  %in% input$nco_survival_summary_outcome
      )
    
    facet_row <- if (dplyr::n_distinct(df$cdm_name, na.rm = TRUE) > 1) "cdm_name" else "."
    facet_col <- if (dplyr::n_distinct(df$outcome,  na.rm = TRUE) > 1) "outcome"  else "."
    facets <- stats::as.formula(paste(facet_row, "~", facet_col))
    
    df <- df |>
      dplyr::mutate(time = as.numeric(.data$time)) |>
      dplyr::filter(.data$time > 0) |>
      dplyr::group_by(.data$cdm_name, .data$outcome, .data$treatment) |>
      dplyr::arrange(.data$time, .by_group = TRUE) |>
      dplyr::filter(dplyr::n() > 1) |>
      dplyr::ungroup() |>
      dplyr::filter(!is.na(.data$survival), .data$survival > 0, .data$survival < 1) |>
      dplyr::mutate(
        cloglog  = log(-log(.data$survival)),
        log_time = log(.data$time)
      )
    
    shiny::validate(
      shiny::need(nrow(df) > 0, "Not enough valid points to build a log(-log) plot.")
    )
    
    df |>
      ggplot2::ggplot(
        ggplot2::aes(
          x = .data$log_time,
          y = .data$cloglog,
          colour = .data$treatment,
          group  = .data$treatment
        )
      ) +
      ggplot2::geom_line(linewidth = 1) +  # clean lines only
      ggplot2::facet_grid(facets) +
      ggplot2::labs(
        x = "log(time)",
        y = "log(-log(survival))"
      ) +
      ggplot2::theme(legend.position = "top")
  })
  
  output$nco_log_minus_log_plot <- shiny::renderPlot({  
    getNCOLogMinusLogPlot()
  })
  

  
  # hr_summary -----
  ## update message if filter is changed
  shiny::observeEvent(input$nco_hr_summary_cdm_name,
                      {
                        updateButtons$nco_hr_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_hr_summary_cohort,
                      {
                        updateButtons$nco_hr_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_hr_summary_variable,
                      {
                        updateButtons$nco_hr_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_hr_summary_outcome,
                      {
                        updateButtons$nco_hr_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_hr_summary_variable_name,
                      {
                        updateButtons$nco_hr_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$nco_hr_summary_estimate_name,
                      {
                        updateButtons$nco_hr_summary <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$nco_hr_summary, {
    if (updateButtons$nco_hr_summary == TRUE) {
      output$update_message_nco_hr_summary <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_nco_hr_summary <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_nco_hr_summary, {
    updateButtons$nco_hr_summary <- FALSE
  })
  
  ## get hr_summary data
  getNCOHrSummaryData <- shiny::eventReactive(input$update_nco_hr_summary, {
    data[["nco_hr_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$nco_hr_summary_cdm_name,
        .data$estimate_name %in% input$nco_hr_summary_estimate_name, 
      ) |>
      omopgenerics::filterGroup(.data$cohort %in% input$nco_hr_summary_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$nco_hr_summary_outcome)
  })

  getNCOHrSummaryTable <- shiny::reactive({
    getNCOHrSummaryData() |>
      simpleTable(
        header = "cdm_name",
        group = c("cohort", "outcome"), 
        hide = "variable_name", 
        rename = c("Variable" = "variable_level")
      )
  })
  output$nco_hr_summary_table <- gt::render_gt({
    getNCOHrSummaryTable()
  })
  output$nco_hr_summary_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$nco_hr_summary_table_format),
    content = function(file) {
      gt::gtsave(getNCOHrSummaryTable(), file)
    }
  )
  
  # calibration plot -----
  ## update message if filter is changed
  shiny::observeEvent(input$calibration_cdm_name,
                      {
                        updateButtons$calibration_plot <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$calibration_cohort,
                      {
                        updateButtons$calibration_plot <- TRUE
                      },
                      ignoreInit = TRUE
  )

  shiny::observeEvent(input$calibration_outcome,
                      {
                        updateButtons$calibration_plot <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(input$calibration_nco,
                      {
                        updateButtons$calibration_plot <- TRUE
                      },
                      ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$calibration_plot, {
    if (updateButtons$calibration_plot == TRUE) {
      output$update_message_calibration <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_calibration <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_calibration, {
    updateButtons$calibration_plot <- FALSE
  })
  
  ## get hr_summary data
  getNegatives <- shiny::eventReactive(input$update_calibration, {
    data[["nco_hr_summary"]] |>
      omopgenerics::filterStrata(!(.data$outcome %in% c("diverticulosis", "hemorrhoids", "constipation")))|>
      dplyr::filter(
        .data$cdm_name %in% input$calibration_cdm_name) |>
      omopgenerics::filterGroup(.data$cohort %in% input$calibration_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$calibration_nco)|>
      dplyr::select(cdm_name, group_level, strata_level, estimate_name, estimate_value) |>
      tidyr::pivot_wider(names_from = "estimate_name", values_from = "estimate_value") |>
      dplyr::mutate(
        coef = as.numeric(coef),
        se_coef = as.numeric(se_coef)
      ) |>
      dplyr::rename(
        logRr = coef,
        seLogRr = se_coef
      ) 
  })
  
  getPositives <- shiny::eventReactive(input$update_calibration, {
    data[["hr_summary"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$calibration_cdm_name) |>
      omopgenerics::filterGroup(.data$cohort %in% input$calibration_cohort) |>
      omopgenerics::filterStrata(.data$outcome %in% input$calibration_outcome)|>
      dplyr::select(cdm_name, group_level, strata_level, estimate_name, estimate_value) |>
      tidyr::pivot_wider(names_from = "estimate_name", values_from = "estimate_value") |>
      dplyr::mutate(
        coef = as.numeric(coef),
        se_coef = as.numeric(se_coef)
      ) |>
      dplyr::rename(
        logRr = coef,
        seLogRr = se_coef
      ) 
  })
  
  getCalibrationPlot <- shiny::reactive({
   negatives <- getNegatives()
   positives <- getPositives()
   null <- fitNull(logRr = negatives$logRr, seLogRr = negatives$seLogRr)
   plotCalibrationEffect(logRrNegatives = negatives$logRr,
                         seLogRrNegatives = negatives$seLogRr,
                         logRrPositives = positives$logRr,
                         seLogRrPositives = positives$seLogRr,
                         null = null)
   
  })
  output$calibration_plot <- shiny::renderUI({
    x <- getCalibrationPlot()
    renderInteractivePlot(x, input$calibration_plot_interactive)
  })
  output$calibrated_forest_plot_download <- shiny::downloadHandler(
    filename = "empirical_calibration_plot.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getCalibrationPlot(),
        width = as.numeric(input$calibration_plot_width),
        height = as.numeric(input$calibration_plot_height),
        units = input$calibration_plot_units,
        dpi = as.numeric(input$calibration_plot_dpi)
      )
    }
  )

  
  getCalibratedCI <- shiny::reactive({
    negatives <- getNegatives() |>
      dplyr::mutate(true_coef = 0)
    positives <- getPositives()
    
    calibrationModel <- fitSystematicErrorModel(logRr = negatives$logRr, 
                                                seLogRr = negatives$seLogRr, 
                                                trueLogRr = negatives$true_coef)
    
    calibrated_pos <- calibrateConfidenceInterval(
      positives$logRr, 
      positives$seLogRr, 
      calibrationModel
    )
    calibrated_results <- positives |> dplyr::select( "cdm_name", "cohort" = "group_level", "outcome" = "strata_level", "coef" = "logRr",
                                                     "se_coef" = "seLogRr", "z", "p", "hr", "lower_hr", "upper_hr") |>
      dplyr::mutate(adjustment = "None", 
                    z = as.numeric(.data$z), 
                    p = as.numeric(.data$p), 
                    hr = as.numeric(.data$hr),
                    lower_hr = as.numeric(.data$lower_hr), 
                    upper_hr = as.numeric(.data$upper_hr))|>
      dplyr::bind_rows(positives |> dplyr::select( "cdm_name", "cohort" = "group_level", "outcome" = "strata_level") |> dplyr::bind_cols(
        calibrated_pos|>
          dplyr::rename(
            "coef" = "logRr",
            "se_coef" = "seLogRr"
          ) |>
          dplyr::mutate(
            hr = exp(.data$coef),
            z = NA,
            p = NA,
            lower_hr = exp(logLb95Rr),
            upper_hr = exp(logUb95Rr),
            adjustment = "calibrated"
          ) |>
          dplyr::select(-c("logLb95Rr", "logUb95Rr"))
      ))|>
      tidyr::pivot_longer(
        cols = c("coef",  "se_coef", "hr",  "z","p","lower_hr","upper_hr"), 
        names_to = "estimate_name", 
        values_to = "estimate_value") |>
      dplyr::mutate(estimate_type = "numeric", 
                    variable_name = "variable", 
                    variable_level = "treatmentRP", 
                    result_id = 1L, 
                    estimate_value = sprintf("%.3f", .data$estimate_value)) |>
      dplyr::arrange(.data$cdm_name, .data$adjustment) |>
      omopgenerics::uniteGroup(cols = "cohort") |>
      omopgenerics::uniteStrata(cols = "outcome") |>
      omopgenerics::uniteAdditional(cols = "adjustment") |>
      omopgenerics::newSummarisedResult()
    
  })
  
  getCalibratedCITable <- shiny::reactive({
    getCalibratedCI() |>
      omopgenerics::filterAdditional(.data$adjustment %in% input$hr_table_adjustment ) |>
      simpleTable(
        header = c("cdm_name", "adjustment"),
        group = c("cohort", "outcome"), 
        hide = "variable_name", 
        rename = c("Variable" = "variable_level")
      )
  })
  output$calibrated_ci_table <- gt::render_gt({
    getCalibratedCITable()
  })
  output$calibrated_ci_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$calibrated_ci_table_format),
    content = function(file) {
      gt::gtsave(getCalibratedCITable(), file)
    }
  )
  getCalibratedForestPlot <- shiny::reactive({
    res <- getCalibratedCI() |>
      omopgenerics::filterAdditional(.data$adjustment == input$adjustment ) |>
      omopgenerics::tidy() |>
      dplyr::mutate(
        coef = as.numeric(coef),
        se_coef = as.numeric(se_coef)
      ) |>
      dplyr::rename(
        logRr = coef,
        seLogRr = se_coef
      ) 
    plotForest(
      res$logRr,
      res$seLogRr,
      res$outcome)
  })
  output$calibrated_forest_plot <- shiny::renderUI({
    x <- getCalibratedForestPlot()
    renderInteractivePlot(x, input$calibrated_forest_plot_interactive)
  })
  output$calibrated_forest_plot_download <- shiny::downloadHandler(
    filename = "forest_plot.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getCalibratedForestPlot(),
        width = as.numeric(input$calibrated_forest_plot_width),
        height = as.numeric(input$calibrated_forest_plot_height),
        units = input$calibrated_forest_plot_units,
        dpi = as.numeric(input$calibrated_forest_plot_dpi)
      )
    }
  )

}


